swagger:
  title: ${info.app.description}
  basePackage: com.letscode.api.starwars.controller
  enabled: true

info:
  app:
    description: Star Wars Trade Outpost API

spring:
  application:
    name: Star Wars API
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2console/